/**
 * @author H.Nakazawa
 * @since  2025-09-15
 */
@isTest
public class naklab_TestConfig {
    
    //*********************************************************************************************
    //   Test Commnet Series
    //*********************************************************************************************

    // Assert Comment
    public static final String ASSERT_COMMENT = 'The result of the execution is not the expected value.';

    //*********************************************************************************************
    //   Test Useful Series
    //*********************************************************************************************
    
    // Test String
    public static final String TEST_STRING = 'TEST';
    // Cron String
    public static final String CRON_STRING = '0 0 * * * ?';
    // Datetime Format String
    public static final String DATETIME_FORMAT_STRING = 'yyyyMMddHHmmssSSS';

}