/**
 * @author H.Nakazawa
 * @since  2025-09-16
 */
@isTest
public class naklab_TestExtendedTriggerHandler extends naklab_TriggerHandler {
    
    /**
     * @author H.Nakazawa
     * @since  2025-09-16
     * @return `List<SObject>`
     */
    public List<SObject> newList(){ return newList; }

    /**
     * @author H.Nakazawa
     * @since  2025-09-16
     * @return `List<SObject>`
     */
    public List<SObject> oldList(){ return oldList; }
    
    /**
     * @author H.Nakazawa
     * @since  2025-09-16
     * @return `Map<Id,SObject>`
     */
    public Map<Id,SObject> newMap(){ return newMap; }

    /**
     * @author H.Nakazawa
     * @since  2025-09-16
     * @return `Map<Id,SObject>`
     */
    public Map<Id,SObject> oldMap(){ return oldMap; }

}