/**
 * @author H.Nakazawa
 * @since  2025-02-08
 */
public class naklab_TestExtendedCoreScheduler extends naklab_CoreScheduler {

    /**
     * @author H.Nakazawa
     * @since  2025-02-08
     */
    public naklab_TestExtendedCoreScheduler(){}

    /**
     * @author H.Nakazawa
     * @since  2025-02-08
     * @param  context
     */
    public override void execute( System.SchedulableContext context ){}

}