/**
 * @author H.Nakazawa
 * @since  2025-02-08
 */
@isTest
public class naklab_TestExtendedCoreQueueProcessor extends naklab_CoreQueueProcessor {
    
    /**
     * @author H.Nakazawa
     * @since  2025-02-08
     */
    public naklab_TestExtendedCoreQueueProcessor(){}

    /**
     * @author H.Nakazawa
     * @since  2025-02-08
     * @param  context
     */
    public override void execute( System.QueueableContext context ){}

}